"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var _11_herencia_1 = require("./11_herencia");
var miCarro = new _11_herencia_1.Vehiculo('Toyota', 'Sedán');
console.log(miCarro.marca);
console.log(miCarro.tipo);
miCarro.moverse();
var miMoto = new _11_herencia_1.Moto('Honda', 'Deportiva');
console.log(miMoto.marca);
console.log(miMoto.tipo);
miMoto.moverse();
